apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccp
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ccp
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ccp
subjects:
- kind: ServiceAccount
  name: ccp
roleRef:
  kind: Role
  name: ccp
  apiGroup: rbac.authorization.k8s.io
