apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccp
spec:
  selector:
    matchLabels:
      app: ccp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ccp
    spec:
      serviceAccountName: ccp
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: wait-for
        image: ghcr.io/patrickdappollonio/wait-for:latest
        command:
        - /wait-for
        args:
        - --host="mysql.ccp:3306"
        - --verbose
      volumes:
      - name: shared-dir
        emptyDir: {}
      containers:
      - name: archivematica-ccp
        image: ghcr.io/artefactual-labs/ccp:latest
        command: ["/var/archivematica/bin/ccp", "server"]
        env:
        - name: CCP_DEBUG
          value: "true"
        - name: CCP_V
          value: "10"
        - name: CCP_SHARED_DIR
          value: "/var/archivematica/sharedDirectory"
        - name: CCP_DB_DRIVER
          value: "mysql"
        - name: CCP_DB_DSN
          value: "root:admin@tcp(mysql.ccp.svc.cluster.local:3306)/CCP"
        - name: CCP_API_ADMIN_ADDR
          value: ":8000"
        - name: CCP_WEBUI_ADDR
          value: ":8001"
        - name: CCP_GEARMIN_ADDR
          value: ":4730"
        ports:
        - name: admin-api
          containerPort: 8000
        - name: web-ui
          containerPort: 8001
        - name: gearmin
          containerPort: 4730
        volumeMounts:
        - name: shared-dir
          mountPath: /var/archivematica/sharedDirectory
      - name: archivematica-worker
        image: ghcr.io/artefactual-labs/ccp:latest
        command: ["pyenv", "exec", "python", "-m", "worker"]
        env:
        - name: DJANGO_SECRET_KEY
          value: "12345"
        - name: ARCHIVEMATICA_WORKER_GEARMAN_SERVER
          value: "localhost:4730"
        - name: ARCHIVEMATICA_WORKER_DB_USER
          value: "root"
        - name: ARCHIVEMATICA_WORKER_DB_PASSWORD
          value: "admin"
        - name: ARCHIVEMATICA_WORKER_DB_HOST
          value: "mysql.ccp.svc.cluster.local"
        - name: ARCHIVEMATICA_WORKER_DB_DATABASE
          value: "CCP"
        volumeMounts:
        - name: shared-dir
          mountPath: /var/archivematica/sharedDirectory
