apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccp-migrate
spec:
  schedule: "0 * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ccp
          restartPolicy: Never
          containers:
          - name: ccp-migrate
            image: ghcr.io/artefactual-labs/ccp:latest
            command: ["pyenv", "exec", "python", "/src/worker/manage.py", "migrate", "--noinput"]
            env:
            - name: DJANGO_SECRET_KEY
              value: "12345"
            - name: ARCHIVEMATICA_WORKER_DB_USER
              value: "root"
            - name: ARCHIVEMATICA_WORKER_DB_PASSWORD
              value: "admin"
            - name: ARCHIVEMATICA_WORKER_DB_HOST
              value: "mysql.ccp.svc.cluster.local"
            - name: ARCHIVEMATICA_WORKER_DB_DATABASE
              value: "CCP"

