// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/controller/dispatcher/dispatcher.go
//
// Generated by this command:
//
//	mockgen -typed -source=./internal/controller/dispatcher/dispatcher.go -destination=./internal/controller/dispatcher/dispatchermock/dispatcher_mock.go -package=dispatchermock Backend
//

// Package dispatchermock is a generated GoMock package.
package dispatchermock

import (
	context "context"
	reflect "reflect"

	dispatcher "github.com/artefactual-labs/ccp/internal/controller/dispatcher"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockBackend) Dispatch(ctx context.Context, jobID uuid.UUID, exec string, tasks []*dispatcher.Task) ([]*dispatcher.TaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, jobID, exec, tasks)
	ret0, _ := ret[0].([]*dispatcher.TaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockBackendMockRecorder) Dispatch(ctx, jobID, exec, tasks any) *MockBackendDispatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockBackend)(nil).Dispatch), ctx, jobID, exec, tasks)
	return &MockBackendDispatchCall{Call: call}
}

// MockBackendDispatchCall wrap *gomock.Call
type MockBackendDispatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBackendDispatchCall) Return(arg0 []*dispatcher.TaskResult, arg1 error) *MockBackendDispatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBackendDispatchCall) Do(f func(context.Context, uuid.UUID, string, []*dispatcher.Task) ([]*dispatcher.TaskResult, error)) *MockBackendDispatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBackendDispatchCall) DoAndReturn(f func(context.Context, uuid.UUID, string, []*dispatcher.Task) ([]*dispatcher.TaskResult, error)) *MockBackendDispatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockBackend) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBackendMockRecorder) Name() *MockBackendNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBackend)(nil).Name))
	return &MockBackendNameCall{Call: call}
}

// MockBackendNameCall wrap *gomock.Call
type MockBackendNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBackendNameCall) Return(arg0 string) *MockBackendNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBackendNameCall) Do(f func() string) *MockBackendNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBackendNameCall) DoAndReturn(f func() string) *MockBackendNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
