// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/controller/dispatcher/workhub.go
//
// Generated by this command:
//
//	mockgen -typed -source=./internal/controller/dispatcher/workhub.go -destination=./internal/controller/dispatcher/dispatchermock/workhub_mock.go -package=dispatchermock workhubSubmitter
//

// Package dispatchermock is a generated GoMock package.
package dispatchermock

import (
	context "context"
	reflect "reflect"

	workerv1beta1 "github.com/artefactual-labs/ccp/internal/api/gen/archivematica/ccp/worker/v1beta1"
	gomock "go.uber.org/mock/gomock"
)

// MockworkhubSubmitter is a mock of workhubSubmitter interface.
type MockworkhubSubmitter struct {
	ctrl     *gomock.Controller
	recorder *MockworkhubSubmitterMockRecorder
	isgomock struct{}
}

// MockworkhubSubmitterMockRecorder is the mock recorder for MockworkhubSubmitter.
type MockworkhubSubmitterMockRecorder struct {
	mock *MockworkhubSubmitter
}

// NewMockworkhubSubmitter creates a new mock instance.
func NewMockworkhubSubmitter(ctrl *gomock.Controller) *MockworkhubSubmitter {
	mock := &MockworkhubSubmitter{ctrl: ctrl}
	mock.recorder = &MockworkhubSubmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockworkhubSubmitter) EXPECT() *MockworkhubSubmitterMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockworkhubSubmitter) Submit(ctx context.Context, fn string, tasks []*workerv1beta1.Task) (map[string]*workerv1beta1.TaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, fn, tasks)
	ret0, _ := ret[0].(map[string]*workerv1beta1.TaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockworkhubSubmitterMockRecorder) Submit(ctx, fn, tasks any) *MockworkhubSubmitterSubmitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockworkhubSubmitter)(nil).Submit), ctx, fn, tasks)
	return &MockworkhubSubmitterSubmitCall{Call: call}
}

// MockworkhubSubmitterSubmitCall wrap *gomock.Call
type MockworkhubSubmitterSubmitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockworkhubSubmitterSubmitCall) Return(arg0 map[string]*workerv1beta1.TaskResult, arg1 error) *MockworkhubSubmitterSubmitCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockworkhubSubmitterSubmitCall) Do(f func(context.Context, string, []*workerv1beta1.Task) (map[string]*workerv1beta1.TaskResult, error)) *MockworkhubSubmitterSubmitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockworkhubSubmitterSubmitCall) DoAndReturn(f func(context.Context, string, []*workerv1beta1.Task) (map[string]*workerv1beta1.TaskResult, error)) *MockworkhubSubmitterSubmitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
