// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.1
// Revision: a6f63bddde05aca4221df9c8e9e6d7d9674b1cb4
// Build Date: 2025-03-18T23:42:14Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// JobStatusUnknown is a JobStatus of type Unknown.
	JobStatusUnknown JobStatus = iota
	// JobStatusAwaitingDecision is a JobStatus of type AwaitingDecision.
	JobStatusAwaitingDecision
	// JobStatusCompletedSuccessfully is a JobStatus of type CompletedSuccessfully.
	JobStatusCompletedSuccessfully
	// JobStatusExecutingCommands is a JobStatus of type ExecutingCommands.
	JobStatusExecutingCommands
	// JobStatusFailed is a JobStatus of type Failed.
	JobStatusFailed
)

var ErrInvalidJobStatus = fmt.Errorf("not a valid JobStatus, try [%s]", strings.Join(_JobStatusNames, ", "))

const _JobStatusName = "UnknownAwaitingDecisionCompletedSuccessfullyExecutingCommandsFailed"

var _JobStatusNames = []string{
	_JobStatusName[0:7],
	_JobStatusName[7:23],
	_JobStatusName[23:44],
	_JobStatusName[44:61],
	_JobStatusName[61:67],
}

// JobStatusNames returns a list of possible string values of JobStatus.
func JobStatusNames() []string {
	tmp := make([]string, len(_JobStatusNames))
	copy(tmp, _JobStatusNames)
	return tmp
}

var _JobStatusMap = map[JobStatus]string{
	JobStatusUnknown:               _JobStatusName[0:7],
	JobStatusAwaitingDecision:      _JobStatusName[7:23],
	JobStatusCompletedSuccessfully: _JobStatusName[23:44],
	JobStatusExecutingCommands:     _JobStatusName[44:61],
	JobStatusFailed:                _JobStatusName[61:67],
}

// String implements the Stringer interface.
func (x JobStatus) String() string {
	if str, ok := _JobStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("JobStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x JobStatus) IsValid() bool {
	_, ok := _JobStatusMap[x]
	return ok
}

var _JobStatusValue = map[string]JobStatus{
	_JobStatusName[0:7]:                    JobStatusUnknown,
	strings.ToLower(_JobStatusName[0:7]):   JobStatusUnknown,
	_JobStatusName[7:23]:                   JobStatusAwaitingDecision,
	strings.ToLower(_JobStatusName[7:23]):  JobStatusAwaitingDecision,
	_JobStatusName[23:44]:                  JobStatusCompletedSuccessfully,
	strings.ToLower(_JobStatusName[23:44]): JobStatusCompletedSuccessfully,
	_JobStatusName[44:61]:                  JobStatusExecutingCommands,
	strings.ToLower(_JobStatusName[44:61]): JobStatusExecutingCommands,
	_JobStatusName[61:67]:                  JobStatusFailed,
	strings.ToLower(_JobStatusName[61:67]): JobStatusFailed,
}

// ParseJobStatus attempts to convert a string to a JobStatus.
func ParseJobStatus(name string) (JobStatus, error) {
	if x, ok := _JobStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _JobStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return JobStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidJobStatus)
}

func (x JobStatus) Ptr() *JobStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x JobStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *JobStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseJobStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errJobStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *JobStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = JobStatus(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = JobStatus(v)
	case string:
		*x, err = ParseJobStatus(v)
	case []byte:
		*x, err = ParseJobStatus(string(v))
	case JobStatus:
		*x = v
	case int:
		*x = JobStatus(v)
	case *JobStatus:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = *v
	case uint:
		*x = JobStatus(v)
	case uint64:
		*x = JobStatus(v)
	case *int:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = JobStatus(*v)
	case *int64:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = JobStatus(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = JobStatus(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = JobStatus(*v)
	case *uint:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = JobStatus(*v)
	case *uint64:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x = JobStatus(*v)
	case *string:
		if v == nil {
			return errJobStatusNilPtr
		}
		*x, err = ParseJobStatus(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x JobStatus) Value() (driver.Value, error) {
	return x.String(), nil
}

// Set implements the Golang flag.Value interface func.
func (x *JobStatus) Set(val string) error {
	v, err := ParseJobStatus(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *JobStatus) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *JobStatus) Type() string {
	return "JobStatus"
}
