version: "2"

run:
  timeout: 1m

linters:
  default: standard
  enable:
    - contextcheck
    - gosec
    - importas
    - intrange
    - misspell
    - unparam
    - usetesting
  settings:
    importas:
      alias:
        - pkg: github.com/artefactual-labs/ccp/internal/api/gen/archivematica/ccp/admin/v1beta1
          alias: adminv1
        - pkg: github.com/artefactual-labs/ccp/internal/api/gen/archivematica/ccp/admin/v1beta1/adminv1beta1connect
          alias: adminv1connect
        - pkg: github.com/artefactual-labs/ccp/internal/api/gen/archivematica/ccp/worker/v1beta1
          alias: workerv1
        - pkg: github.com/artefactual-labs/ccp/internal/api/gen/archivematica/ccp/worker/v1beta1/workerv1beta1connect
          alias: workerv1connect
      no-unaliased: true
      no-extra-aliases: false
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - hack
      - proto
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: strict
    paths:
      - hack
      - proto
      - third_party$
      - builtin$
      - examples$
