# Generated by Django 4.2.16 on 2025-06-25 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0083_unpickle_access_target"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="job",
            index_together={
                ("sipuuid", "jobtype", "createdtime", "createdtimedec"),
                ("unittype", "sipuuid", "createdtime", "createdtimedec"),
                (
                    "sipuuid",
                    "currentstep",
                    "microservicegroup",
                    "microservicechainlink",
                ),
                ("jobtype", "currentstep"),
                ("sipuuid", "createdtime", "createdtimedec"),
            },
        ),
    ]
