---

services:
  archivematica-tests:
    image: "archivematica-tests:latest"
    build:
      context: "../"
      dockerfile: "hack/Dockerfile"
      target: "archivematica-tests"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12.4}
    volumes:
      - "../:/src"
    links:
      - "mysql"
