---
name: ccp

volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  mysql_data:

  # External named volumes.
  # These are intended to be accessible beyond the docker host (e.g. via NFS).
  # They use bind mounts to mount a specific "local" directory on the docker
  # host - the expectation being that these directories are actually mounted
  # filesystems from elsewhere.
  archivematica_pipeline_data:
    name: "ccp-am-pipeline-data"
    external: true

services:

  mysql:
    image: "percona:8.0"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      # These are used in the settings.testmysql modules
      MYSQL_USER: "archivematica"
      MYSQL_PASSWORD: "demo"
    volumes:
      - "./etc/mysql/tuning.cnf:/etc/my.cnf.d/tuning.cnf:ro"
      - "mysql_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:63001:3306"
    cap_add:
      - "SYS_NICE"

  archivematica-ccp:
    build:
      context: "../"
      target: "archivematica-ccp"
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    entrypoint: ["/home/ccp/bin/ccp", "server"]
    restart: "on-failure"
    environment:
      - "CCP_DEBUG=true"
      - "CCP_V=10"
      - "CCP_SHARED_DIR=/var/archivematica/sharedDirectory"
      - "CCP_DB_DRIVER=mysql"
      - "CCP_DB_DSN=root:12345@tcp(mysql:3306)/CCP"
      - "CCP_API_ADMIN_ADDR=:8000"
      - "CCP_WEBUI_ADDR=:8001"
      - "CCP_METRICS_ADDR=:7999"
    volumes:
      - "./submodules/archivematica-sampledata/:/home/archivematica/archivematica-sampledata/:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
    ports:
      - "63030:8000"
      - "63031:8001"

  archivematica-worker:
    build:
      context: "../"
      target: "archivematica-worker"
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12.5}
    environment:
      DJANGO_SECRET_KEY: "12345"
      ARCHIVEMATICA_WORKER_GEARMAN_SERVER: "archivematica-ccp:4730"
      ARCHIVEMATICA_WORKER_CAPTURE_CLIENT_SCRIPT_OUTPUT: "true"
      ARCHIVEMATICA_WORKER_PROMETHEUS_BIND_PORT: "7999"
      ARCHIVEMATICA_WORKER_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
      ARCHIVEMATICA_WORKER_DB_USER: "archivematica"
      ARCHIVEMATICA_WORKER_DB_PASSWORD: "demo"
      ARCHIVEMATICA_WORKER_DB_HOST: "mysql"
      ARCHIVEMATICA_WORKER_DB_DATABASE: "CCP"
    volumes:
      - "../worker:/src"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "archivematica-ccp"
