# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: gen
generate:
  std-http-server: true
  strict-server: true
  models: true
  embedded-spec: true
output: gen/shim.go
output-options:
  name-normalizer: ToCamelCaseWithInitialisms
  disable-type-aliases-for-type: []
compatibility:
  always-prefix-enum-values: true
