package dispatcher

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"time"

	"github.com/artefactual-labs/gearmin"
	"github.com/go-logr/logr"
	"github.com/google/uuid"

	"github.com/artefactual-labs/ccp/internal/cmd/servercmd/metrics"
	"github.com/artefactual-labs/ccp/internal/store"
	"github.com/artefactual-labs/ccp/internal/workflow"
)

type TaskRequest struct {
	Arguments        string
	StdoutFile       string
	StderrFile       string
	FileID           uuid.UUID
	RelativeLocation string
}

func (r TaskRequest) captureOutput() bool {
	return r.StdoutFile != "" || r.StderrFile != ""
}

type TaskResult struct {
	ExitCode   int
	CreatedAt  time.Time
	FinishedAt time.Time
}

// Task is a unit of work to be executed by a backend.
type Task struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Request   *TaskRequest
}

type Backend interface {
	Name() string
	Dispatch(ctx context.Context, jobID uuid.UUID, exec string, tasks []*Task) ([]*TaskResult, error)
}

// Dispatcher is responsible for dispatching tasks to the appropriate backend
// for execution. It uses a router to select the appropriate backend based.
// Currently, it supports two backends: gearmin and workhub. The gearmin backend
// is used for executing tasks in MCPClient, while the workhub backend is used
// for executing tasks in the new workhub system.
type Dispatcher struct {
	logger   logr.Logger
	metrics  *metrics.Metrics
	store    store.Store
	router   backendRouter
	backends map[string]Backend
}

func New(logger logr.Logger, metrics *metrics.Metrics, store store.Store, gearmin *gearmin.Server, submitter workhubSubmitter) (*Dispatcher, error) {
	gearminBackend := newGearminBackend(logger.WithName(gearminBackendID), metrics, store, gearmin)
	workhubBackend := newWorkhubBackend(logger.WithName(workhubBackendID), metrics, store, submitter)
	backends := map[string]Backend{
		gearminBackend.Name(): gearminBackend,
		workhubBackend.Name(): workhubBackend,
	}

	d := &Dispatcher{
		logger:   logger,
		metrics:  metrics,
		store:    store,
		router:   DefaultBackendRouter,
		backends: backends,
	}

	return d, nil
}

func NewWithBackend(logger logr.Logger, metrics *metrics.Metrics, store store.Store, backend Backend) *Dispatcher {
	return &Dispatcher{
		logger:  logger,
		metrics: metrics,
		store:   store,
		router: func(backends map[string]Backend, linkConfig *workflow.LinkStandardTaskConfig) Backend {
			return backend
		},
	}
}

// Dispatch prepares tasks and sends them to the selected backend for execution.
func (d *Dispatcher) Dispatch(ctx context.Context, jobID uuid.UUID, linkConfig *workflow.LinkStandardTaskConfig, requests []*TaskRequest) ([]*TaskResult, error) {
	if len(requests) == 0 {
		return []*TaskResult{}, nil
	}

	// Select the backend implementation.
	backend := d.router(d.backends, linkConfig)
	d.logger.Info("Dispatching tasks.", "backend", backend.Name(), "total", len(requests))

	tasks := make([]*Task, len(requests))
	for i, req := range requests {
		tasks[i] = &Task{
			ID:        uuid.New(),
			CreatedAt: time.Now().UTC(),
			Request:   req,
		}
	}

	return backend.Dispatch(ctx, jobID, linkConfig.Execute, tasks)
}

// writeOutput writes given contents to the provided file path.
//
// Some workflow client jobs are expected to write the standard output streams
// (stdout and stderr) generated by worker functions to disk. This helper
// centralizes that logic, ensuring output is written to the correct location
// with appropriate permissions, and that directories are created as needed.
//
//	$ jq '.. | .stdout_file?, .stderr_file? | select(. != null)' workflow.json | sort | uniq -c
//	      4 "%SIPLogsDirectory%clamAVScan.txt"
//	      2 "%SIPLogsDirectory%extractContents.log"
//	     10 "%SIPLogsDirectory%fileFormatIdentification.log"
//	     10 "%SIPLogsDirectory%filenameChanges.log"
//	      5 "%SIPLogsDirectory%FileUUIDsError.log"
//	      5 "%SIPLogsDirectory%FileUUIDs.log"
//	      2 "%SIPLogsDirectory%handles.log"
//	      6 "%SIPLogsDirectory%removedFilesWithNoPremisMetadata.log"
//	      6 "%SIPLogsDirectory%removeUnneededFiles.log"
//	      2 "%SIPLogsDirectory%SIPnameCleanup.log"
//	      2 "%SIPLogsDirectory%verifyChecksumsInFileSecOfDSpaceMETSFiles.log"
//
// TODO: can we stop doing this?
func writeOutput(filePath string, contents any) (err error) {
	const (
		// Append, create and write to the file (the "a" mode in Python).
		fileFlags = os.O_APPEND | os.O_CREATE | os.O_WRONLY

		// TODO: investigate why MCPServer was using 0o750 and not 0o640.
		fileMode = 0o750
	)

	if filePath == "" {
		return nil
	}

	// TODO: move directory creation elsewhere.
	dir := filepath.Dir(filePath)
	if dir != "" {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return err
		}
	}

	f, err := os.OpenFile(filePath, fileFlags, fileMode)
	if err != nil {
		return err
	}
	defer func() {
		closeErr := f.Close()
		err = errors.Join(err, closeErr)
	}()

	if s, ok := any(contents).(string); ok {
		_, err = f.WriteString(s)
	} else if b, ok := any(contents).([]byte); ok {
		_, err = f.Write(b)
	}
	if err != nil {
		return err
	}

	// Ensure that the file permissions are set.
	return os.Chmod(filePath, fileMode)
}
