name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo hello world
