name: Tests
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: hack/ccp/go.mod
          cache-dependency-path: hack/ccp/go.sum
      - name: Run tests
        run: go test -race ./...
        working-directory: hack/ccp
