{
 "title": "Archivematica",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Pipeline Overview - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Last AIP stored",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(worker_aips_stored_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
    }
   ]
  },
  {
   "title": "Last Transfer started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(worker_transfer_started_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
    }
   ]
  },
  {
   "title": "Last DIP stored",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(worker_dips_stored_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
    }
   ]
  },
  {
   "title": "In progress packages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_active_packages{instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "AIPs stored",
   "type": "singlestat",
   "description": "Increase over the selected time range",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(increase(worker_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))",
     "legendFormat": "AIPs stored"
    }
   ]
  },
  {
   "title": "Transfers started",
   "type": "singlestat",
   "description": "Increase over the selected time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(increase(worker_transfer_started_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))"
    }
   ]
  },
  {
   "title": "DIPs stored",
   "type": "singlestat",
   "description": "Increase over the selected time range",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(increase(worker_dips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))",
     "legendFormat": "AIPs stored"
    }
   ]
  },
  {
   "title": "Archivematica version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "archivematica_version_info{job=~\"[[job]]\", instance=~\"[[instance]]\"}"
    }
   ]
  },
  { "title": "Processing Details - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "job" },
  {
   "title": "Transfers processed",
   "type": "graph",
   "description": "For all worker, averaged over the selected time range, e.g. per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "transfers" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(worker_transfer_started_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "Transfers started"
    },
    {
     "expr": "sum by (job)(round(increase(worker_transfer_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "Transfer errors"
    },
    {
     "expr": "sum by (job)(round(increase(worker_transfer_completed_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "Transfers completed"
    }
   ]
  },
  {
   "title": "Packages stored",
   "type": "graph",
   "description": "By all workers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "packages" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(worker_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "AIPs stored"
    },
    {
     "expr": "sum by (job)(round(increase(worker_dips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "DIPs stored "
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(increase(worker_aip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) or sum by (job)(increase(worker_aip_size_bytes_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "AIPs"
    },
    {
     "expr": "sum by (job)(increase(worker_dip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) or sum by (job)(increase(worker_dip_size_bytes_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "DIP bytes"
    },
    {
     "expr": "sum by (job)(increase(worker_transfer_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "Transfer bytes"
    }
   ]
  },
  {
   "title": "Processing errors",
   "type": "graph",
   "description": "Across the pipeline, averaged over the time range given, e.g. per hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(worker_transfer_error_total{job=~\"[[job]]\", failure_type=\"fail\"}[1m])))",
     "legendFormat": "Transfer error"
    },
    {
     "expr": "sum by (job)(round(increase(worker_transfer_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"reject\"}[$__interval])))",
     "legendFormat": "Transfer rejected"
    },
    {
     "expr": "sum by (job)(round(increase(worker_sip_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"fail\"}[$__interval])))",
     "legendFormat": "SIP error"
    },
    {
     "expr": "sum by (job)(round(increase(worker_sip_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"reject\"}[$__interval])))",
     "legendFormat": "SIP rejected"
    }
   ]
  },
  {
   "title": "Files processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(worker_aip_files_stored_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) or sum by (job)(round(increase(worker_aip_files_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "AIP files stored"
    },
    {
     "expr": "sum by (job)(round(increase(worker_transfer_files_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "Transfer files ingested"
    }
   ]
  },
  {
   "title": "File Processing Analysis - $job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "job"
  },
  {
   "title": "Average number of files - AIPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "  (sum by (job) (rate(worker_aip_files_stored_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job) (rate(worker_aip_files_stored_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) or (sum by (job) (rate(worker_aip_files_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job) (rate(worker_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average number of files - Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (transfer_type) (rate(worker_transfer_files_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (transfer_type) (rate(worker_transfer_files_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "{{ transfer_type }}"
    }
   ]
  },
  {
   "title": "AIP number of files distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_aip_files_stored_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Transfer number of files distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_transfer_files_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average AIP size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (job) (rate(worker_aip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job) (rate(worker_aip_size_bytes_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) or (sum by (job)(rate(worker_aip_size_bytes_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job)(rate(worker_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average Transfer size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (transfer_type)(rate(worker_transfer_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (transfer_type)(rate(worker_transfer_size_bytes_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "{{ transfer_type }}"
    }
   ]
  },
  {
   "title": "AIP size distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_aip_size_bytes_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Transfer size distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_transfer_size_bytes_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "File formats processed - Derivatives",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (format_name) (round(increase(worker_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"derivative\"}[$__interval])) != 0)",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File formats processed - Originals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "files " }
   ],
   "targets": [
    {
     "expr": "sum by (format_name) (round(increase(worker_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"original\"}[$__interval])) != 0)",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File formats processed - Metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (format_name) (round(increase(worker_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"metadata\"}[$__interval])) != 0)",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File modification year distribution",
   "type": "heatmap",
   "description": "original files only.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_aip_original_file_timestamps_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Performance Analysis - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }, "repeat": "job" },
  {
   "title": "Average AIP processing time",
   "type": "graph",
   "description": "Average processing time over the past minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(worker_aip_processing_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job)(rate(worker_aip_processing_seconds_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average DIP processing time",
   "type": "graph",
   "description": "Average processing time over the past minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(worker_dip_processing_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) / sum by (job)(rate(worker_dip_processing_seconds_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "DIP processing time"
    }
   ]
  },
  {
   "title": "AIP processing time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_aip_processing_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "DIP processing time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_dip_processing_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "increase(django_http_requests_total_by_method_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])",
     "legendFormat": "{{ method }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "sum by (type, instance)(rate(django_http_exceptions_total_by_type_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "{{ type }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total task execution time (Worker)",
   "type": "bargauge",
   "description": "Total time spent over the selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "topk(5, sum by (script_name) (increase(worker_task_execution_time_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))",
     "legendFormat": "{{ script_name  }}"
    }
   ]
  },
  {
   "title": "Total task execution time (CCP)",
   "type": "bargauge",
   "description": "Total time spent over the selected time range. May vary from worker ass erver is often waiting for client processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(mcpserver_task_duration_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])) by (script_name))",
     "legendFormat": "{{ script_name  }}"
    }
   ]
  },
  { "title": "Developer Info - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 }, "repeat": "job" },
  {
   "title": "Gearman pending jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 115 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_gearman_pending_jobs{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Gearman active jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 115 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_gearman_active_jobs{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Job queue length",
   "type": "singlestat",
   "description": "Length of the CCP job queue for *active* packages",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 115 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_active_package_job_queue_length{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "CCP task duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum(round(increase(mcpserver_task_duration_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "CCP tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(mcpserver_task_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (job)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(round(increase(mcpserver_task_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (job)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Worker task duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(round(increase(worker_task_execution_time_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Worker jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "jobs" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(worker_job_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (instance)",
     "legendFormat": "Completed - {{instance}}"
    },
    {
     "expr": "sum(round(increase(worker_job_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))) by (instance)",
     "legendFormat": "Errored - {{instance}}"
    }
   ]
  },
  {
   "title": "Average HTTP request time by view",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])",
     "legendFormat": "{{ method}}: {{ view}}"
    }
   ]
  },
  {
   "title": "Django model updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short", "label": "saves" }
   ],
   "targets": [
    {
     "expr": "sum(increase(django_model_save_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval])) by (model)",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "CPU time by python process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(irate(process_cpu_seconds_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}